[general]
import = ["themes/snazzy.toml", "themes/noctalia.toml"]

[bell]
animation = "EaseOutExpo"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"


[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"


[scrolling]
history = 100000

# [shell]
# args = ["--login", "-c", "tmux attach || tmux new -s main"]
# program = "/bin/zsh"

[window]
dynamic_title = true
opacity = 0.88
