
[desktop]

[desktop.files]
"config/qq-bwrap-flags.conf" = "~/.config/qq-bwrap-flags.conf"
"config/wechat-universal" = { type = "symbolic", target = "~/.config/wechat-universal", recurse = false }
"config/wofi" = { type = "symbolic", target = "~/.config/wofi", recurse = false }
"config/mpd" = { type = "symbolic", target = "~/.config/mpd", recurse = false }
"config/flameshot" = { type = "symbolic", target = "~/.config/flameshot", recurse = false }
"config/dunst" = { type = "symbolic", target = "~/.config/dunst", recurse = false }
"config/quickshell" = { type = "symbolic", target = "~/.config/quickshell", recurse = false }

"config/libinput-gestures.conf" = "~/.config/libinput-gestures.conf"
"config/yay" = { type = "symbolic", target = "~/.config/yay", recurse = false }

"config/hypr" = { type = "symbolic", target = "~/.config/hypr", recurse = false }

"config/microsoft-edge-stable-flags.conf" = "~/.config/microsoft-edge-stable-flags.conf"
"config/electron-flags.conf" = "~/.config/electron-flags.conf"
"config/code-flags.conf" = "~/.config/code-flags.conf"
