
[desktop.files]
"config/kitty" = { type = "symbolic", target = "~/.config/kitty", recurse = false }
"config/alacritty" = { type = "symbolic", target = "~/.config/alacritty", recurse = false }
"config/wezterm" = { type = "symbolic", target = "~/.config/wezterm", recurse = false }

[vim.files]
"config/nvim" = { type = "symbolic", target = "~/.config/nvim", recurse = false }

[shell.files]
"home/zshrc" = "~/.zshrc"
"home/zshenv" = "~/.zshenv"

"home/p10k.zsh" = "~/.p10k.zsh"

"home/tmux.conf.local" = "~/.tmux.conf.local"

"config/yazi" = { type = "symbolic", target = "~/.config/yazi", recurse = false }

[mirror.files]
"config/pip" = { type = "symbolic", target = "~/.config/pip", recurse = false }
"home/cargo/config.toml" = "~/.cargo/config.toml"
"home/bunfig.toml" = "~/.bunfig.toml"
"home/condarc" = "~/.condarc"
"home/npmrc" = "~/.npmrc"
"home/default-cargo-crates" = "~/.default-cargo-crates"
