secret: "xxx"

pp: &pp
  type: http
  interval: 86400
  health-check:
    enable: true
    url: "https://www.gstatic.com/generate_204"
    interval: 300
  exclude-filter: "套餐|流量|群组|频道|官网|推荐使用|测试|电报|订阅|地址|佣金"
  header:
    User-Agent:
      - "clash-verge/v2.4.3"

proxy-providers:
  airport:
    !!merge <<: *pp
    url: "https://xxxx"
