secret: "xxx"
proxy-providers:
  airport:
    url: "https://xxxx"
    type: http
    interval: 86400
    health-check:
      {
        enable: true,
        url: "https://www.gstatic.com/generate_204",
        interval: 300,
      }
    exclude-filter: "套餐|流量|群组|频道|官网|推荐使用|测试|电报|订阅|地址"
    header:
      User-Agent:
        - "clash-verge/v2.4.3"
proxy-groups:
  - name: "AIRPORT"
    type: url-test
    url: "https://www.gstatic.com/generate_204"
    interval: 500
    use:
      - airport
rule-providers:
  airport:
    behavior: classical
    url: "https://xxxx"
    type: http
    interval: 86400
### Inspired by https://github.com/Loyalsoldier/clash-rules

# 白名单模式，意为「没有命中规则的网络流量，统统使用代理」，适用于服务器线路网络质量稳定、快速，不缺服务器流量的用户。
# rules:
#   - RULE-SET,applications,DIRECT
#   - DOMAIN,clash.razord.top,DIRECT
#   - DOMAIN,yacd.haishan.me,DIRECT
#   - RULE-SET,private,DIRECT
#   - RULE-SET,reject,REJECT
#   - RULE-SET,icloud,DIRECT
#   - RULE-SET,aiple,DIRECT
#   - RULE-SET,google,AIRPORT
#   - RULE-SET,proxy,AIRPORT
#   - RULE-SET,direct,DIRECT
#   - RULE-SET,lancidr,DIRECT
#   - RULE-SET,cncidr,DIRECT
#   - RULE-SET,telegramcidr,AIRPORT
#   - GEOIP,LAN,DIRECT
#   - GEOIP,CN,DIRECT
#   - MATCH,AIRPORT

# 黑名单模式，意为「只有命中规则的网络流量，才使用代理」，适用于服务器线路网络质量不稳定或不够快，或服务器流量紧缺的用户。通常也是软路由用户、家庭网关用户的常用模式。
rules:
  - RULE-SET,applications,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,AIRPORT
  - RULE-SET,gfw,AIRPORT
  - RULE-SET,telegramcidr,AIRPORT
  - DOMAIN-SUFFIX,*.local,DIRECT
  - IP-CIDR,172.18.36.0/24,easyconnect
  - IP-CIDR,10.16.87.0/24,easyconnect
  - MATCH,DIRECT
