mixed-port: 8090
external-controller: 127.0.0.1:8092
geodata-mode: true
geo-auto-update: false
# ç­–ç•¥ç»„ç›¸å…³
pr: &pr
  type: select
  proxies:
    - é»˜è®¤
    - é¦™æ¸¯
    - é¦™æ¸¯è‡ªåŠ¨é€‰æ‹©
    - å°æ¹¾
    - å°æ¹¾è‡ªåŠ¨é€‰æ‹©
    - æ—¥æœ¬
    - æ—¥æœ¬è‡ªåŠ¨é€‰æ‹©
    - æ–°åŠ å¡
    - æ–°åŠ å¡è‡ªåŠ¨é€‰æ‹©
    - ç¾å›½
    - ç¾å›½è‡ªåŠ¨é€‰æ‹©
    - å…¶å®ƒåœ°åŒº
    - å…¨éƒ¨èŠ‚ç‚¹
    - è‡ªåŠ¨é€‰æ‹©
    - ç›´è¿
proxies:
  - name: "ç›´è¿"
    type: direct
    udp: true
proxy-groups:
  - {
      name: é»˜è®¤,
      type: select,
      proxies:
        [
          è‡ªåŠ¨é€‰æ‹©,
          ç›´è¿,
          é¦™æ¸¯,
          é¦™æ¸¯è‡ªåŠ¨é€‰æ‹©,
          å°æ¹¾,
          å°æ¹¾è‡ªåŠ¨é€‰æ‹©,
          æ—¥æœ¬,
          æ—¥æœ¬è‡ªåŠ¨é€‰æ‹©,
          æ–°åŠ å¡,
          æ–°åŠ å¡è‡ªåŠ¨é€‰æ‹©,
          ç¾å›½,
          ç¾å›½è‡ªåŠ¨é€‰æ‹©,
          å…¶å®ƒåœ°åŒº,
          å…¨éƒ¨èŠ‚ç‚¹,
        ],
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png",
    }
  - {
      name: Google,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png",
    }
  - {
      name: Apple,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png",
    }
  - {
      name: Telegram,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png",
    }
  - {
      name: Twitter,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Twitter.png",
    }
  - {
      name: ehentai,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Panda.png",
    }
  - {
      name: å“”å“©å“”å“©,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/bilibili.png",
    }
  - {
      name: å“”å“©ä¸œå—äºš,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/bilibili.png",
    }
  - {
      name: å·´å“ˆå§†ç‰¹,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Bahamut.png",
    }
  - {
      name: YouTube,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png",
    }
  - {
      name: NETFLIX,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png",
    }
  - {
      name: Spotify,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Spotify.png",
    }
  - {
      name: ChatGPT,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ChatGPT.png",
    }
  - {
      name: å›½å†…,
      type: select,
      proxies:
        [
          ç›´è¿,
          é»˜è®¤,
          é¦™æ¸¯,
          é¦™æ¸¯è‡ªåŠ¨é€‰æ‹©,
          å°æ¹¾,
          å°æ¹¾è‡ªåŠ¨é€‰æ‹©,
          æ—¥æœ¬,
          æ—¥æœ¬è‡ªåŠ¨é€‰æ‹©,
          æ–°åŠ å¡,
          æ–°åŠ å¡è‡ªåŠ¨é€‰æ‹©,
          ç¾å›½,
          ç¾å›½è‡ªåŠ¨é€‰æ‹©,
          å…¶å®ƒåœ°åŒº,
          å…¨éƒ¨èŠ‚ç‚¹,
          è‡ªåŠ¨é€‰æ‹©,
        ],
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China_Map.png",
    }
  - {
      name: å…¶ä»–,
      !!merge <<: *pr,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png",
    }
  #åˆ†éš”,ä¸‹é¢æ˜¯åœ°åŒºåˆ†ç»„
  - {
      name: é¦™æ¸¯,
      type: select,
      include-all: true,
      filter: "(?i)(?!ç›´è¿)(æ¸¯|hk|hongkong|hong kong)",
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/HK.png",
    }
  - {
      name: å°æ¹¾,
      type: select,
      include-all: true,
      filter: "(?i)(?!ç›´è¿)(å°|tw|taiwan)",
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TW.png",
    }
  - {
      name: æ—¥æœ¬,
      type: select,
      include-all: true,
      filter: "(?i)(?!ç›´è¿)(æ—¥|jp|japan)",
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/JP.png",
    }
  - {
      name: ç¾å›½,
      type: select,
      include-all: true,
      filter: "(?i)(?!ç›´è¿)(ç¾|us|unitedstates|united states)",
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/US.png",
    }
  - {
      name: æ–°åŠ å¡,
      type: select,
      include-all: true,
      filter: "(?i)(?!ç›´è¿)(æ–°|sg|singapore)",
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/SG.png",
    }
  - {
      name: å…¶å®ƒåœ°åŒº,
      type: select,
      include-all: true,
      filter: "(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¯ğŸ‡µ|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¨ğŸ‡³|æ¸¯|hk|hongkong|å°|tw|taiwan|æ—¥|jp|japan|æ–°|sg|singapore|ç¾|us|unitedstates|ç›´è¿)).*",
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Available.png",
    }
  - {
      name: è‡ªåŠ¨é€‰æ‹©,
      type: url-test,
      include-all: true,
      tolerance: 10,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Auto.png",
    }
  - {
      name: å…¨éƒ¨èŠ‚ç‚¹,
      type: select,
      include-all: true,
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png",
    }
  - {
      name: é¦™æ¸¯è‡ªåŠ¨é€‰æ‹©,
      type: url-test,
      include-all: true,
      filter: "(?i)(?!ç›´è¿)(æ¸¯|hk|hongkong|hong kong)",
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/HK.png",
    }
  - {
      name: å°æ¹¾è‡ªåŠ¨é€‰æ‹©,
      type: url-test,
      include-all: true,
      filter: "(?i)(?!ç›´è¿)(å°|tw|taiwan)",
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TW.png",
    }
  - {
      name: æ—¥æœ¬è‡ªåŠ¨é€‰æ‹©,
      type: url-test,
      include-all: true,
      filter: "(?i)(?!ç›´è¿)(æ—¥|jp|japan)",
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/JP.png",
    }
  - {
      name: ç¾å›½è‡ªåŠ¨é€‰æ‹©,
      type: url-test,
      include-all: true,
      filter: "(?i)(?!ç›´è¿)(ç¾|us|unitedstates|united states)",
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/US.png",
    }
  - {
      name: æ–°åŠ å¡è‡ªåŠ¨é€‰æ‹©,
      type: url-test,
      include-all: true,
      filter: "(?i)(æ–°|sg|singapore)",
      icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/SG.png",
    }
rules:
  - DOMAIN-SUFFIX,local,ç›´è¿
  - GEOIP,lan,ç›´è¿,no-resolve
  - RULE-SET, scholar_domain,ç›´è¿
  - RULE-SET,biliintl_domain,å“”å“©ä¸œå—äºš
  - RULE-SET,ehentai_domain,ehentai
  - RULE-SET,github_domain,å…¶ä»–
  - RULE-SET,twitter_domain,Twitter
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,google_domain,Google
  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,netflix_domain,NETFLIX
  - RULE-SET,bilibili_domain,å“”å“©å“”å“©
  - RULE-SET,bahamut_domain,å·´å“ˆå§†ç‰¹
  - RULE-SET,spotify_domain,Spotify
  - RULE-SET,pixiv_domain,å…¶ä»–
  - RULE-SET,geolocation-!cn,å…¶ä»–
  - RULE-SET,google_ip,Google
  - RULE-SET,netflix_ip,NETFLIX
  - RULE-SET,telegram_ip,Telegram
  - RULE-SET,twitter_ip,Twitter
  - RULE-SET,chatgpt_domain,ChatGPT
  - RULE-SET,cn_domain,å›½å†…
  - RULE-SET,cn_ip,å›½å†…
  - MATCH,å…¶ä»–
rule-anchor:
  ip: &ip { type: http, interval: 86400, behavior: ipcidr, format: text }
  domain:
    &domain { type: http, interval: 86400, behavior: domain, format: text }
rule-providers:
  private:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.list"
  cn_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.list"
  biliintl_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/biliintl.list"
  ehentai_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ehentai.list"
  github_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.list"
  twitter_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.list"
  youtube_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.list"
  google_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.list"
  telegram_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.list"
  netflix_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.list"
  bilibili_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.list"
  bahamut_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bahamut.list"
  spotify_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.list"
  pixiv_domain:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/pixiv.list"
  geolocation-!cn:
    !!merge <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.list"
  cn_ip:
    !!merge <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.list"
  google_ip:
    !!merge <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.list"
  netflix_ip:
    !!merge <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.list"
  twitter_ip:
    !!merge <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.list"
  telegram_ip:
    !!merge <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.list"
  chatgpt_domain:
    type: http
    behavior: classical
    interval: 86400
    url: "https://raw.githubusercontent.com/G4free/clash-ruleset/main/ruleset/ChatGPT.yaml"
  scholar_domain:
    type: http
    behavior: classical
    format: yaml
    interval: 86400
    url: "https://cdn.jsdelivr.net/gh/ferristale/clash_rules_for_scholar/rules/scholar.yaml"
