# for ArchLinux
# includes = [".dotter/platform/arch.toml", ".dotter/platform/unix.toml"]
# packages = ["develop", "desktop"]

# for windows
# includes = [".dotter/platform/windows.toml"]
# packages = ["develop", "desktop"]


[variables]
# email="xxx@example.com"
# git_username="Your name"
# config_path="your $XDG_CONFIG_HOME"
