# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
    # Help
    { on = ["?"], run = "help", desc = "Open help" },
    { on = ["s"], run = "plugin keyjump --args=global" },
    { on = ["\\", "f", "f"], run = "search fd" },
    { on = ["\\", "f", "w"], run = "search rg" },

    { on = "/", run = "filter --smart", desc = "Filter files" },
    { on = "f", run = "plugin jump-to-char", desc = "Jump to char" },
]
[help]
keymap = [
    { on = "<Esc>", run = "escape", desc = "Clear the filter, or hide the help" },
    { on = "/", run = "filter", desc = "Apply a filter for the help items" },

]
