# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
    # Help
    { on = [
        "?",
    ], run = "help", desc = "Open help" },
    # { on = ["\\", "f", "f"], run = "search fd" },
    # { on = ["\\", "f", "w"], run = "search rg" },

    { on = "/", run = "filter --smart", desc = "Filter files" },
    { on = "s", run = "plugin jump-to-char", desc = "Jump to char" },
    { on = "z", run = "plugin zoxide", desc = "Jump to a directory using zoxide" },
    { on = "Z", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
    { on = [
        "M",
        "m",
    ], run = "plugin mount", desc = "Mount filesystem" },
    { on = [
        "c",
        "m",
    ], run = "plugin chmod", desc = "Chmod on selected files" },

    { on = [
        "M",
        "s",
    ], run = "plugin sshfs -- menu", desc = "Open SSHFS options" },
]
[help]
keymap = [
    { on = "<Esc>", run = "escape", desc = "Clear the filter, or hide the help" },
    { on = "/", run = "filter", desc = "Apply a filter for the help items" },

]
