services:
  easyconnect:
    container_name: easyconnect
    image: docker.io/hagb/docker-easyconnect:cli
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - /dev/net/tun:/dev/net/tun
    environment:
      EC_VER: 7.6.7
      CLI_OPTS: "-d ${EC_DOMAIN} -u ${EC_USERNAME} -p ${EC_PASSWORD}"
    ports:
      - "8093:1080"
      - "8094:8888"
