
[env]

RUSTUP_DIST_SERVER="https://mirrors.ustc.edu.cn/rust-static"
RUSTUP_UPDATE_ROOT="https://mirrors.ustc.edu.cn/rust-static/rustup"


[settings]
idiomatic_version_file_enable_tools = []



# node.mirror_url="https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/"
npm.bun=true

[tools]
bun = "latest"
node = "24"
pnpm = "latest"
ruff = "latest"
rust = "nightly"
tree-sitter = "latest"
usage = "latest"
yazi = "latest"
