
[env]
RUSTUP_DIST_SERVER="https://mirrors.tuna.tsinghua.edu.cn/rustup"


[settings]
idiomatic_version_file_enable_tools = []



# node.mirror_url="https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/"
npm.bun=true

[tools]
bun = "latest"
node = "24"
pnpm = "latest"
rust = "nightly"
tree-sitter = "latest"
yazi = "latest"
