[env]

RUSTUP_DIST_SERVER = "https://mirrors.ustc.edu.cn/rust-static"
RUSTUP_UPDATE_ROOT = "https://mirrors.ustc.edu.cn/rust-static/rustup"


[settings]
idiomatic_version_file_enable_tools = []
experimental = true
lockfile = true
node.gpg_verify = false

# node.mirror_url="https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/"
npm.bun = true

[tools]
bun = "latest"
"github:anomalyco/opencode" = "latest"
lazygit = "latest"
node = "24.12.0"
ruff = "0.14.8"
rust = "nightly"
tree-sitter = "0.26.1"
usage = "2.11.0"
uv = "latest"
